<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1592869588263' stop='1592869635349'>
    <name>Connection</name>
    <title>Connection</title>
    <test-cases>
        <test-case start='1592869609655' status='failed' stop='1592869634775'>
            <name>In-place</name>
            <title>In-place</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1592869609656' status='undefined'>
                    <name>Can start in-place connection</name>
                    <title>Can start in-place connection</title>
                    <attachments>
                        <attachment title='Test failed: Connection :: In-place' source='188b1d49-8598-432e-b9da-e868d73f84dd-attachment.png' type='image/png' size='32908'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Protocol error (Page.captureScreenshot): Cannot take screenshot with 0 width.</message>
                <stack-trace>Error: Protocol error (Page.captureScreenshot): Cannot take screenshot with 0 width.
                    at Promise (/home/travis/build/Automattic/jetpack/node_modules/puppeteer/lib/Connection.js:183:56)
                    at new Promise (&lt;anonymous>)
                    at CDPSession.send (/home/travis/build/Automattic/jetpack/node_modules/puppeteer/lib/Connection.js:182:12)
                    at Page._screenshotTask (/home/travis/build/Automattic/jetpack/node_modules/puppeteer/lib/Page.js:948:39)
                    at process._tickCallback (internal/process/next_tick.js:68:7)
                  -- ASYNC --
                    at Page.&lt;anonymous> (/home/travis/build/Automattic/jetpack/node_modules/puppeteer/lib/helper.js:111:15)
                    at screenshot (/home/travis/build/Automattic/jetpack/tests/e2e/lib/reporters/screenshot.js:15:13)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>