<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1595581527993' stop='1595581565449'>
    <name>Connection</name>
    <title>Connection</title>
    <test-cases>
        <test-case start='1595581529841' status='failed' stop='1595581563807'>
            <name>In-place</name>
            <title>In-place</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1595581529842' status='passed' stop='1595581543221'>
                    <name>Can start in-place connection</name>
                    <title>Can start in-place connection</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1595581543221' status='undefined'>
                    <name>Can assert that site is connected</name>
                    <title>Can assert that site is connected</title>
                    <attachments>
                        <attachment title='Test failed: Connection :: In-place' source='6d035564-b27f-40c1-b08f-1ff9c5531b19-attachment.png' type='image/png' size='237968'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: expect(received).toBeTruthy()
                
                Received: false</message>
                <stack-trace>Error: expect(received).toBeTruthy()
                
                Received: false
                    at toBeTruthy (/home/travis/build/Automattic/jetpack/tests/e2e/specs/connection.test.js:35:46)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>