<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1594206176254' stop='1594206188968'>
    <name>Connection</name>
    <title>Connection</title>
    <test-cases>
        <test-case start='1594206182130' status='failed' stop='1594206188968'>
            <name>In-place</name>
            <title>In-place</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1594206182130' status='passed' stop='1594206188342'>
                    <name>Can login</name>
                    <title>Can login</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1594206188342' status='undefined'>
                    <name>Can start in-place connection</name>
                    <title>Can start in-place connection</title>
                    <attachments>
                        <attachment title='Test failed: Connection :: In-place' source='2fc2aa7b-0aba-4348-a9eb-52d70b09e68e-attachment.png' type='image/png' size='230122'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>ReferenceError: wpcomUser is not defined</message>
                <stack-trace>ReferenceError: wpcomUser is not defined
                    at wpcomUser (/home/travis/build/Automattic/jetpack/tests/e2e/specs/connection.test.js:38:32)
                    at tryCatch (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.(anonymous function) [as next] (/home/travis/build/Automattic/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
                    at new Promise (&lt;anonymous>)
                    at /home/travis/build/Automattic/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12
                    at fn (/home/travis/build/Automattic/jetpack/tests/e2e/lib/setup-env.js:173:8)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>