<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1604144094330' stop='1604144242976'>
    <name>Paid blocks</name>
    <title>Paid blocks</title>
    <test-cases>
        <test-case start='1604144135864' status='failed' stop='1604144149203'>
            <name>MailChimp Block</name>
            <title>MailChimp Block</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1604144135865' status='passed' stop='1604144140792'>
                    <name>Can visit the block editor and add a MailChimp block</name>
                    <title>Can visit the block editor and add a MailChimp block</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1604144140792' status='passed' stop='1604144146628'>
                    <name>Can connect to a MailChimp</name>
                    <title>Can connect to a MailChimp</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1604144146628' status='passed' stop='1604144149187'>
                    <name>Can publish a post and assert that MailChimp block is rendered</name>
                    <title>Can publish a post and assert that MailChimp block is rendered</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Site does not have complete plan</message>
                <stack-trace>Error: Site does not have complete plan
                    at _callee4$ (/home/runner/work/jetpack/jetpack/tests/e2e/lib/flows/jetpack-connect.js:110:9)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1604144149203' status='failed' stop='1604144157525'>
            <name>Pay with PayPal</name>
            <title>Pay with PayPal</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1604144149204' status='passed' stop='1604144151960'>
                    <name>Can visit the block editor and add a Pay with PayPal block</name>
                    <title>Can visit the block editor and add a Pay with PayPal block</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1604144151960' status='passed' stop='1604144155635'>
                    <name>Can fill details of Pay with PayPal block</name>
                    <title>Can fill details of Pay with PayPal block</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1604144155635' status='passed' stop='1604144157502'>
                    <name>Can publish a post and assert that Pay with PayPal block is rendered</name>
                    <title>Can publish a post and assert that Pay with PayPal block is rendered</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Site does not have complete plan</message>
                <stack-trace>Error: Site does not have complete plan
                    at _callee4$ (/home/runner/work/jetpack/jetpack/tests/e2e/lib/flows/jetpack-connect.js:110:9)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1604144157525' status='failed' stop='1604144236404'>
            <name>WordAds block</name>
            <title>WordAds block</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1604144157526' status='undefined'>
                    <name>Can visit the block editor and add a WordAds block</name>
                    <title>Can visit the block editor and add a WordAds block</title>
                    <attachments>
                        <attachment title='Test failed: Paid blocks :: WordAds block' source='2fb9db9d-f1e5-469a-a4c3-9eddbc54bd42-attachment.png' type='image/png' size='32032'/>
                    </attachments>
                    <steps/>
                </step>
            </steps>
            <attachments/>
            <failure>
                <message>Error: Site does not have complete plan</message>
                <stack-trace>Error: Site does not have complete plan
                    at _callee4$ (/home/runner/work/jetpack/jetpack/tests/e2e/lib/flows/jetpack-connect.js:110:9)
                    at tryCatch (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:45:40)
                    at Generator.invoke [as _invoke] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:274:22)
                    at Generator.prototype.&lt;computed> [as next] (/home/runner/work/jetpack/jetpack/node_modules/regenerator-runtime/runtime.js:97:21)
                    at asyncGeneratorStep (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _next (/home/runner/work/jetpack/jetpack/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>